#!/bin/bash
echo Attempting to install pre-reqs
echo run this as S U D O

#Optional Web landingpage
#apt-get install nginix

#Don't ever put your keys in github files...
cp settings.orig settings.py

#Version 3 PIP
apt-get install python3-pip

#Python Twitter Library (install by other means is you need to)
pip3 install tweepy

##Temporary DM Workaround
apt-get install ruby
gem install twurl
